### ISSUE TITLE
Issue with spinner title in layout

### ISSUE THREAD

**Issue by CharlieRegal** [MattJAshworth/SpinnerTools#1]
Version: 1.4.3

The title of the spinner is quite close to the selected item text resulting in a cluttered layout, could we possibly have the options to position this text or atleast have it moved up in the layout? 

![image](https://github.com/user-attachments/assets/717793ff-4ceb-482d-bcfc-a6c0e4e9b30f)

Thanks

**Comment by MattJAshworth** [comment]
I've added an attribute `hint_bottomMargin` to the Spinner view.

```XML
<xyz.mattjashworth.spinnertools.sheet.Spinner
        android:id="@+id/app_spinner"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:hint_bottomMargin="5dp"
       />
```

This is included in build `1.4.4` available via JitPack. Thanks
